# this is a default config file for yolo training remember to change the paths
path: C:\Users\twim\Documents\new_data_set\data
train: C:\Users\twim\Documents\new_data_set\data\images\train
val: C:\Users\twim\Documents\new_data_set\data\images\train

names:
  0: Ball
  1: Robot
  2: Goal
